"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.shapeTypes = exports.maskTypes = exports.layerStyleTypes = exports.layerType = void 0;
var layerType;
(function (layerType) {
    layerType[layerType["precomp"] = 0] = "precomp";
    layerType[layerType["solid"] = 1] = "solid";
    layerType[layerType["still"] = 2] = "still";
    layerType[layerType["nullLayer"] = 3] = "nullLayer";
    layerType[layerType["shape"] = 4] = "shape";
    layerType[layerType["text"] = 5] = "text";
    layerType[layerType["audio"] = 6] = "audio";
    layerType[layerType["pholderVideo"] = 7] = "pholderVideo";
    layerType[layerType["imageSeq"] = 8] = "imageSeq";
    layerType[layerType["video"] = 9] = "video";
    layerType[layerType["pholderStill"] = 10] = "pholderStill";
    layerType[layerType["guide"] = 11] = "guide";
    layerType[layerType["adjustment"] = 12] = "adjustment";
    layerType[layerType["camera"] = 13] = "camera";
    layerType[layerType["light"] = 14] = "light";
    layerType[layerType["data"] = 15] = "data";
})(layerType || (exports.layerType = layerType = {}));
var layerStyleTypes;
(function (layerStyleTypes) {
    layerStyleTypes[layerStyleTypes["stroke"] = 0] = "stroke";
    layerStyleTypes[layerStyleTypes["dropShadow"] = 1] = "dropShadow";
    layerStyleTypes[layerStyleTypes["innerShadow"] = 2] = "innerShadow";
    layerStyleTypes[layerStyleTypes["outerGlow"] = 3] = "outerGlow";
    layerStyleTypes[layerStyleTypes["innerGlow"] = 4] = "innerGlow";
    layerStyleTypes[layerStyleTypes["bevelEmboss"] = 5] = "bevelEmboss";
    layerStyleTypes[layerStyleTypes["satin"] = 6] = "satin";
    layerStyleTypes[layerStyleTypes["colorOverlay"] = 7] = "colorOverlay";
    layerStyleTypes[layerStyleTypes["gradientOverlay"] = 8] = "gradientOverlay";
})(layerStyleTypes || (exports.layerStyleTypes = layerStyleTypes = {}));
var maskTypes;
(function (maskTypes) {
    maskTypes["NONE"] = "n";
    maskTypes["ADD"] = "a";
    maskTypes["SUBTRACT"] = "s";
    maskTypes["INTERSECT"] = "i";
    maskTypes["LIGHTEN"] = "l";
    maskTypes["DARKEN"] = "d";
    maskTypes["DIFFERENCE"] = "f";
})(maskTypes || (exports.maskTypes = maskTypes = {}));
var shapeTypes;
(function (shapeTypes) {
    shapeTypes["shape"] = "sh";
    shapeTypes["rect"] = "rc";
    shapeTypes["ellipse"] = "el";
    shapeTypes["star"] = "sr";
    shapeTypes["fill"] = "fl";
    shapeTypes["gfill"] = "gf";
    shapeTypes["gStroke"] = "gs";
    shapeTypes["stroke"] = "st";
    shapeTypes["merge"] = "mm";
    shapeTypes["trim"] = "tm";
    shapeTypes["twist"] = "tw";
    shapeTypes["group"] = "gr";
    shapeTypes["repeater"] = "rp";
    shapeTypes["roundedCorners"] = "rd";
    shapeTypes["offsetPath"] = "op";
    shapeTypes["puckerAndBloat"] = "pb";
    shapeTypes["zigZag"] = "zz";
})(shapeTypes || (exports.shapeTypes = shapeTypes = {}));
//# sourceMappingURL=sticker.js.map